scraper/custom_scraper/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.mainpage_test2, name='mainpage'),

    path('key1/', views.Key1, name='Key1'),
    path('key2/', views.Key2, name='Key2'),
    path('key3/', views.Key3, name='Key3'),
    path('SentimentScore/', views.SentimentScore, name='SentimentScore'),
    path('WordCount/', views.WordCount, name='WordCount'),
    path('word_count/', views.word_count, name="word_count"),
    path('research/', views.research, name='research'),
    path('Sentiment_Main/', views.Sentiment_Main, name='Sentiment_Main'),
    path('sentiment_word/', views.sentiment_word, name='sentiment_word'),
    path('sentiment_date/', views.sentiment_date, name='sentiment_date'),
    path('word_count_session/', views.word_count_session, name='word_count_session'),
    path('date_search/', views.date_search, name='date_search'),
    path('Sentiment/', views.Sentiment, name='Sentiment'),
    path('sentiment_landing/', views.sentiment_landing, name='sentiment_landing'),
    path('overall_sentiment/', views.overall_sentiment, name='overall_sentiment'),
    path('sentiment_overall_ajax/', views.sentiment_overall_ajax, name='sentiment_overall_ajax'),
    path('sentiment_compare/', views.sentiment_compare, name='sentiment_compare'),
    path('sentiment_newspaper/', views.sentiment_newspaper, name='sentiment_newspaper'),
    path('sentiment_word_search/', views.sentiment_word_search, name='sentiment_word_search'),
    path('sentiment_word_search_result/', views.sentiment_word_search_result, name='sentiment_word_search_result'),
    path('sent_compare_search/', views.sent_compare_search, name='sent_compare_search'),
    path('sent_compare_search_result/', views.sent_compare_search_result, name='sent_compare_search_result'),
    path('research_sent/', views.research_sent, name='research_sent'),
    path('research_emotion_compare/', views.research_emotion_compare, name='research_emotion_compare'),
    path('research_emotion_compare_single/', views.research_emotion_compare_single, name='research_emotion_compare_single'),
    path('word_count_general_og/', views.word_count_general_og, name='word_count_general_og'),
    path('word_count_general_db/', views.word_count_general_db, name='word_count_general_db'),
    path('emotion_newspaper/', views.emotion_newspaper, name='emotion_newspaper'),
    path('emotion_compare/', views.emotion_compare, name='emotion_compare'),
    path('emotion_search_compare/', views.emotion_search_compare, name='emotion_search_compare'),
    path('emotion_search_compare_result/', views.emotion_search_compare_result, name='emotion_search_compare_result'),
    path('emotion_search_compare_single/', views.emotion_search_compare_single, name='emotion_search_compare_single'),
    path('emotion_search_compare_result_single/', views.emotion_search_compare_result_single, name='emotion_search_compare_result_single'),
    path('wc_search_compare_result/', views.wc_search_compare_result, name='wc_search_compare_result'),
    path('wc_search_compare/', views.wc_search_compare, name='wc_search_compare'),
    path('wc_search_compare_single/', views.wc_search_compare_single, name='wc_search_compare_single'),
    path('research_wc_compare/', views.research_wc_compare, name='research_wc_compare'),
    path('research_wc_compare_single/', views.research_wc_compare_single, name='research_wc_compare_single'),
    path('wc_search_compare_result_single/', views.wc_search_compare_result_single, name='wc_search_compare_result_single'),
    path('hl_search_compare_single/', views.hl_search_compare_single, name='hl_search_compare_single'),
    path('hl_search_compare_result_single/', views.hl_search_compare_result_single, name='hl_search_compare_result_single'),
    path('research_hl_compare_single/', views.research_hl_compare_single, name='research_hl_compare_single'),
    path('hl_search_compare/', views.hl_search_compare, name='hl_search_compare'),
    path('hl_search_compare_result/', views.hl_search_compare_result, name='hl_search_compare_result'),
    path('research_hl_compare/', views.research_hl_compare, name='research_hl_compare'),
    path('about/', views.about, name='about'),
    path('mainpage_past/', views.mainpage, name='mainpage_past'),
]

scraper/scraper/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('custom_scraper.urls')),
]

scraper/custom_scraper/models.py
from django.db import models
import datetime
from django.utils import timezone
from django import forms
# Create your models here.
class Headline(models.Model):
    headline = models.CharField(max_length=500)
    newspaper = models.PositiveIntegerField()
    date = models.DateTimeField(default=timezone.now)
    link = models.CharField(max_length=1000)
    day_order = models.PositiveIntegerField()
    sentiment = models.DecimalField(max_digits=12, decimal_places=10)

    def __str__(self):
        return self.headline

class Photos(models.Model):
    newspaper = models.PositiveIntegerField()
    keyword = models.CharField(max_length=1000)
    link = models.CharField(max_length=1000)
    date = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.link

class word_sentiment(models.Model):
    date = models.DateTimeField(default=timezone.now)
    word = models.CharField(max_length=500)
    count = models.PositiveIntegerField()
    sentiment = models.DecimalField(max_digits=12, decimal_places=10)
    word_type = models.PositiveIntegerField()

    def __str__(self):
        return self.overall_word


class superlative_table(models.Model):
    graphid = models.PositiveIntegerField()
    date = models.DateTimeField(default=timezone.now)
    newspaper = models.PositiveIntegerField()
    news1 = models.CharField(max_length=10)
    news2 = models.CharField(max_length=10)

    word = models.CharField(max_length=100)
    count = models.PositiveIntegerField()
    sentiment = models.DecimalField(max_digits=12, decimal_places=10)


    def __str__(self):
        return self.word


class variance_table(models.Model):

    graphid = models.PositiveIntegerField()
    date = models.DateTimeField(default=timezone.now)
    variance_date = models.DateTimeField(null=True, blank=True)
    word = models.CharField(max_length=100)
    news1 = models.CharField(max_length=10)
    news2 = models.CharField(max_length=10)
    sentiment = models.DecimalField(max_digits=12, decimal_places=10)


    def __str__(self):
        return self.word

class variance_table_word(models.Model):

    graphid = models.PositiveIntegerField()
    date = models.DateTimeField(default=timezone.now)
    word = models.CharField(max_length=100)
    count = models.PositiveIntegerField()
    news1 = models.CharField(max_length=10)
    news2 = models.CharField(max_length=10)
    sentiment = models.DecimalField(max_digits=12, decimal_places=10)





    def __str__(self):
        return self.word

class Headlinewrl(models.Model):
    headline = models.CharField(max_length=500)
    newspaper = models.PositiveIntegerField()
    date = models.DateTimeField(default=timezone.now)
    link = models.CharField(max_length=1000)
    day_order = models.PositiveIntegerField()
    sentiment = models.DecimalField(max_digits=12, decimal_places=10)
    reading_level = models.DecimalField(max_digits=5, decimal_places=1)


class Headlinewc(models.Model):
    headline = models.CharField(max_length=500)
    newspaper = models.PositiveIntegerField()
    date = models.DateTimeField(default=timezone.now)
    link = models.CharField(max_length=1000)
    day_order = models.PositiveIntegerField()
    sentiment = models.DecimalField(max_digits=12, decimal_places=10)
    reading_level = models.DecimalField(max_digits=5, decimal_places=1)
    headline_wc = models.PositiveIntegerField()

class word_count(models.Model):
    date = models.DateTimeField(default=timezone.now)
    word = models.CharField(max_length=500)
    nyt = models.PositiveIntegerField()
    bbc = models.PositiveIntegerField()
    fn = models.PositiveIntegerField()
    overall = models.PositiveIntegerField()



class cooc(models.Model):
    date = models.DateTimeField(default=timezone.now)
    base_word = models.CharField(max_length=500)
    co_word = models.CharField(max_length=500)
    newspaper = models.PositiveIntegerField()
    co_word_count = models.PositiveIntegerField()


class total_word_count(models.Model):
    date = models.DateTimeField(default=timezone.now)
    word = models.CharField(max_length=500)
    nyt = models.PositiveIntegerField()
    bbc = models.PositiveIntegerField()
    fn = models.PositiveIntegerField()
    overall = models.PositiveIntegerField()

class word_count_general(models.Model):
    date = models.DateTimeField(default=timezone.now)
    newspaper = models.PositiveIntegerField()
    word = models.CharField(max_length=500)
    word_count = models.PositiveIntegerField()

class style_wc(models.Model):
    date = models.DateTimeField(default=timezone.now)
    newspaper = models.PositiveIntegerField()
    awc = models.DecimalField(max_digits=12, decimal_places=4)
    ahrl = models.DecimalField(max_digits=12, decimal_places=4)
    percent_quest = models.DecimalField(max_digits=12, decimal_places=4)
    percent_exclam = models.DecimalField(max_digits=12, decimal_places=4)
    ahwl = models.DecimalField(max_digits=12, decimal_places=4)
    uw = models.DecimalField(max_digits=12, decimal_places=4)
    wd = models.DecimalField(max_digits=12, decimal_places=4)

class cooc_wc(models.Model):
    date = models.DateTimeField(default=timezone.now)
    newspaper = models.PositiveIntegerField()
    base_word = models.CharField(max_length=500)
    cooc = models.CharField(max_length=500)
    coocc = models.PositiveIntegerField()

class emotion(models.Model):
    date = models.DateTimeField(default=timezone.now)
    word = models.CharField(max_length=500)
    fear = models.PositiveIntegerField()
    anger = models.PositiveIntegerField()
    anticip = models.PositiveIntegerField()
    trust = models.PositiveIntegerField()
    surprise = models.PositiveIntegerField()
    positive = models.PositiveIntegerField()
    negative = models.PositiveIntegerField()
    sadness = models.PositiveIntegerField()
    disgust = models.PositiveIntegerField()
    joy = models.PositiveIntegerField()


class Headline_emotion(models.Model):
    headline = models.CharField(max_length=500)
    newspaper = models.PositiveIntegerField()
    date = models.DateTimeField(default=timezone.now)
    link = models.CharField(max_length=1000)
    day_order = models.PositiveIntegerField()
    sentiment = models.DecimalField(max_digits=12, decimal_places=10)
    reading_level = models.DecimalField(max_digits=5, decimal_places=1)
    headline_wc = models.PositiveIntegerField()
    fear = models.PositiveIntegerField()
    anger = models.PositiveIntegerField()
    anticip = models.PositiveIntegerField()
    trust = models.PositiveIntegerField()
    surprise = models.PositiveIntegerField()
    positive = models.PositiveIntegerField()
    negative = models.PositiveIntegerField()
    sadness = models.PositiveIntegerField()
    disgust = models.PositiveIntegerField()
    joy = models.PositiveIntegerField()

class emotion_associated(models.Model):
    date = models.DateTimeField(default=timezone.now)
    newspaper = models.PositiveIntegerField()
    emotion = models.CharField(max_length=500)
    word = models.CharField(max_length=500)
    word_count = models.PositiveIntegerField()




class headline_tokenized(models.Model):
    headline_id = models.PositiveIntegerField()
    newspaper = models.PositiveIntegerField()
    word = models.CharField(max_length=500)



class tokenized_headlines(models.Model):
    headline_id = models.PositiveIntegerField()
    newspaper = models.PositiveIntegerField()
    word = models.CharField(max_length=500)

class headline_id_tokens(models.Model):
    headline_id = models.PositiveIntegerField()
    newspaper = models.PositiveIntegerField()
    word = models.CharField(max_length=500)

class hl_tokenized_id(models.Model):
    headline_id = models.PositiveIntegerField()
    newspaper = models.PositiveIntegerField()
    word = models.CharField(max_length=500)


class hl_tokens(models.Model):
    headline_id = models.PositiveIntegerField()
    newspaper = models.PositiveIntegerField()
    word = models.CharField(max_length=500)
    date = models.DateTimeField(default=timezone.now)
    link = models.CharField(max_length=1000)
    day_order = models.PositiveIntegerField()


class hl_tokens_emotions(models.Model):
    headline_id = models.PositiveIntegerField()
    newspaper = models.PositiveIntegerField()
    word = models.CharField(max_length=500)
    date = models.DateTimeField(default=timezone.now)
    link = models.CharField(max_length=1000)
    day_order = models.PositiveIntegerField()
    fear = models.PositiveIntegerField()
    anger = models.PositiveIntegerField()
    anticip = models.PositiveIntegerField()
    trust = models.PositiveIntegerField()
    surprise = models.PositiveIntegerField()
    positive = models.PositiveIntegerField()
    negative = models.PositiveIntegerField()
    sadness = models.PositiveIntegerField()
    disgust = models.PositiveIntegerField()
    joy = models.PositiveIntegerField()


class top_words_emotions(models.Model):
    date = models.DateTimeField(default=timezone.now)
    newspaper = models.PositiveIntegerField()
    word = models.CharField(max_length=500)
    fear = models.PositiveIntegerField()
    anger = models.PositiveIntegerField()
    anticip = models.PositiveIntegerField()
    trust = models.PositiveIntegerField()
    surprise = models.PositiveIntegerField()
    sadness = models.PositiveIntegerField()
    disgust = models.PositiveIntegerField()
    joy = models.PositiveIntegerField()
    fear_percent = models.DecimalField(max_digits=5, decimal_places=2)
    anger_percent = models.DecimalField(max_digits=5, decimal_places=2)
    anticip_percent = models.DecimalField(max_digits=5, decimal_places=2)
    trust_percent = models.DecimalField(max_digits=5, decimal_places=2)
    surprise_percent = models.DecimalField(max_digits=5, decimal_places=2)
    sadness_percent = models.DecimalField(max_digits=5, decimal_places=2)
    disgust_percent = models.DecimalField(max_digits=5, decimal_places=2)
    joy_percent = models.DecimalField(max_digits=5, decimal_places=2)

scraper/custom_scraper/forms.py
from django import forms

class WordCountSearch(forms.Form):
    word_count = forms.CharField(label='',max_length=120, widget=forms.TextInput(attrs={'placeholder':'Search Headlines'}))

class SentimentWordSearch(forms.Form):
    sentiment_word_search = forms.CharField(max_length=120, label = '', widget=forms.TextInput(attrs={'placeholder':'Enter Search Term Here'}))

class SentimentDateSearch(forms.Form):
    sentiment_date_search = forms.DateField(label = '', widget=forms.TextInput(attrs={'placeholder':'Enter Date Here'}))

class DateForm(forms.Form):
    date = forms.DateField(input_formats=['%d/%m/%Y'], widget=forms.TextInput(attrs={'placeholder':'Enter Date'}))

class CompareSearch1(forms.Form):
    compare1 = forms.CharField(label='',max_length=120, widget=forms.TextInput(attrs={'placeholder':'First Term'}))
    compare2 = forms.CharField(label='',max_length=120, widget=forms.TextInput(attrs={'placeholder':'Second Term'})) 

class CompareSearch2(forms.Form):
    compare2 = forms.CharField(label='',max_length=120, widget=forms.TextInput(attrs={'placeholder':'Second Term'}))

class CompareSearchSingle(forms.Form):
    compare1 = forms.CharField(label='',max_length=120, widget=forms.TextInput(attrs={'placeholder':'Enter Term'}))

scraper/custom_scraper/templates/custom_scraper/Sentiment.html
<html> 
<head>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;1,900&display=swap" rel="stylesheet">
<style>
.sent_heat_grid {
    display:grid;
    grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr 1fr;
    padding:30px;
    

}
body {
  font-family:"Roboto";
}
.invisible {
   background-color:gray;
  
}

.green1 {
background-color:#86c48d;


}
.green2 {
background-color:#5db066;
}

.green3 {
background-color:#0c8a19;
}

.red1 {
background-color:#f78b8b;
}

.red2 {
background-color:#f55353;
}

.red3 {
  background-color:#e60000;
}
.compare_grid {
  display:grid;
  grid-template-columns:1fr 1fr;
  width:1000px;
  height:500px;
 
}
 .top_bar {
    position:fixed;
    width:100%;
  }
    .header {
    font-family:"Roboto";
    font-size:30px;
    font-weight:900;
    text-align:center;
    padding-bottom: 7px;
    
    background:white;
    width:80%;
    margin:auto;
    
  }

  .header a{
  text-decoration:none;
  color:black;
}
.header a:hover{
  text-decoration:underline;
  color:black;
}  

.header a:visited {
  text-decoration:none;
  color:black;
}
.navbar {
  padding-left:20px;
  padding-right:20px;
  display:flex;
  flex-direction:row;
  justify-content: space-between;
  font-size:15px;
  font-weight: normal;
  font-family:"Roboto";
  border-top:3px solid black;
  border-bottom: 1px solid gray;
  padding-top:3px;
  padding-bottom:3px;
  width:80%;
  margin:auto;
}

    .nav_current a {
  text-decoration:none;
  color:white;
      background:#5a6069;
      border: 1px solid black;
      border-radius:5px;
      padding:8px;
      
}

 .nav a {
  text-decoration:none;
  color:black;
}

.nav a:hover {
  text-decoration: underline;
  text-decoration-color:black;
}

.nav a:visited {
  color:black;
}
    .nav_current a {
  text-decoration:none;
  color:white;
      background:#5a6069;
      border: 1px solid black;
      border-radius:5px;
      padding:8px;
      
}

.main {
  padding-top:200px;
  width:80%;
  margin:auto;
}
</style>
<script>

document.addEventListener("DOMContentLoaded", function(event) { 
    //Do work


  var psentiment = document.getElementsByClassName("invisible");
  
  
  for (a = psentiment.length-1; a >= 0; a--){
    console.log(psentiment[a].innerHTML)
    if(psentiment[a].innerHTML > 0 && psentiment[a].innerHTML <= 5 ){
      console.log(psentiment[a].innerHTML);
      psentiment[a].className = "green1";
    }
    else if(psentiment[a].innerHTML > 5 && psentiment[a].innerHTML <= 8 ){
      psentiment[a].className = "green2";
    }
    else if(psentiment[a].innerHTML > 8){
      psentiment[a].className = "green3";
    }
    else if(psentiment[a].innerHTML < 0 && psentiment[a].innerHTML > -3 ){
      psentiment[a].className = "red1";
    }
    else if(psentiment[a].innerHTML <= -3 && psentiment[a].innerHTML > -6 ){
      psentiment[a].className = "red2";
    }
    else if(psentiment[a].innerHTML <= -6){
      psentiment[a].className = "red3";
    }
  };
});

</script>
</head>
<body>
<div class="top_bar"><div class="header"><a href='{% url 'mainpage' %}'>Headline Compare</a></div>
  <div class="navbar"><div class="nav"><a href=WordCount>Word Count</a></div><div class="nav_current"><a href=Sentiment_Main>Sentiment Score</a></div><div class="nav">Phrase Count</div><div class="nav">Country Count</div><div class="nav">Headline Priority</div> <div class="nav">Deltas</div><div class="nav">Date</div></div></div>
  
<div class="main">

<div class="compare_grid">
<div class="sent_heat_grid">


{% for x, y, z in final_may_list %}
   <div class="invisible"> {{y}} </div>
{% endfor %}


</div>
<div class="sent_heat_grid">

{% for x, y, z in final_may_list_fn %}
   <div class="invisible"> {{y}} </div>
{% endfor %}


</div>
</div>
</div>
</body>


</html>

scraper/custom_scraper/templates/custom_scraper/WordCount.html
<html>
  <head>
          <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;1,900&display=swap" rel="stylesheet">

<style>
  .header {
    font-family:"Roboto";
    font-size:30px;
    font-weight:900;
    text-align:center;
    padding-bottom: 7px;
    
    background:white;
    width:80%;
    margin:auto;
    
  }
  .navbar {
  padding-left:20px;
  padding-right:20px;
  display:flex;
  flex-direction:row;
  justify-content: space-between;
  font-size:15px;
  font-weight: normal;
  font-family:"Roboto";
  border-top:3px solid black;
  border-bottom: 1px solid gray;
  padding-top:3px;
  padding-bottom:3px;
  width:80%;
  margin:auto;
}
  .nav a {
  text-decoration:none;
  color:black;
}

.nav a:hover {
  text-decoration: underline;
  text-decoration-color:black;
}

.nav a:visited {
  color:black;
}
    .nav_current a {
  text-decoration:none;
  color:white;
      background:#5a6069;
      border: 1px solid black;
      border-radius:5px;
      padding:8px;
      
}
  


  .top_bar {
    position:fixed;
    width:100%;
  }
  
  .main_grid {
   
    display:grid;
    grid-template-columns: 1fr;
    justify-items:center;
  }
  
  .main_body {
     padding-top:115px;
    font-family:"Roboto";
    width:80%;
    justify:center;
    margin:auto;
  }

.table_title {
    font-family:"Roboto";
    font-size:30px;
    font-weight:700;
    margin:auto;
    text-align:center;
}
.table_subtitle {
  text-align:center;
}
.top_words {
  width:100%;
}

.header a{
  text-decoration:none;
  color:black;
}
.header a:hover{
  text-decoration:underline;
  color:black;
}  

.header a:visited {
  text-decoration:none;
  color:black;
}

  input[type="submit"] {
         
         font-size: 15px;
         font-family: "Roboto";
         width:90px;
        color:black;
        background:whitesmoke;
        border-radius:5px;
        padding:10px;

     }

     input[type="text"] {
       padding:20px;
       font-size: 15px;
       width: 80%;
     }

     .search {
       width:70%;
       margin:auto;
     }

     .chart {
       padding-top:20px;
     }
  </style>
   
  </head>
  <div class="top_bar"><div class="header"><a href='{% url 'mainpage' %}'>Headline Compare</a></div>
  <div class="navbar"><div class="nav_current"><a href=WordCount>Word Count</a></div><div class="nav"><a href=Sentiment_Main>Sentiment Score</a></div><div class="nav">Phrase Count</div><div class="nav">Country Count</div><div class="nav">Headline Priority</div> <div class="nav">Deltas</div><div class="nav">Date</div></div></div>
  
  <div class="main_body">
  <div class="main_grid"> 
    <div class="top_words">
<div class="table_title">Most Common Words Used in Headlines</div>
<div class="table_subtitle"> (since Jan. 25, 2020)</div>

<div class="chart">
      {% autoescape off %}
    {{ html_div_values }}
{% endautoescape %}  
</div>
    </div>
    
    <div class="search">
    <div class="search">
    <form action="/word_count" method="GET">
           {% csrf_token %}
           {{form}}
            <input type="submit" value="Search">
            </form></div>
    
  
  
  </div>
  </div>
  <body>
  </body>
</html>

scraper/custom_scraper/templates/custom_scraper/WordCountold.html
<html>
    <head>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Alegreya&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Alegreya:900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Carrois+Gothic&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;1,900&display=swap" rel="stylesheet">
    <style>

.navbar-fixed-top {
 
 position: fixed;
 
 right: 0;
 top: 0;
 
 left: 0;
 
 z-index: 999;
 
 
 
 
 
 }
 .navbar-fixed-top:after {
    content: ""; /* This is necessary for the pseudo element to work. */
    display: block; /* This will put the pseudo element on its own line. */
    margin: 0 auto; /* This will center the border. */
    width: 100%; /* Change this to whatever width you want. */
    padding-top: 0px; /* This creates some space between the element and the border. */
    border-bottom: 2px solid black; /* This creates the border. Replace black with whatever color you want. */
}

.topdate {
     
     top:200;
     font-size:50px;
     font-family: "Roboto";
      text-align: center;
      padding-top:48px;
      padding-bottom: 8px;
      z-index:998;
      font-weight: 900;
      padding-right:44px;
     
   }
   .navbar-fixed-date {
 
 position: fixed;
 
 right: 0;
 top: 0;
 
 left: 0;
 
 z-index: 998;
 
 background-color: white;
 
 
 }
 .navbar-fixed-date:after {
    content: ""; /* This is necessary for the pseudo element to work. */
    display: block; /* This will put the pseudo element on its own line. */
    margin: 0 auto; /* This will center the border. */
    width: 80%; /* Change this to whatever width you want. */
    padding-top: 0px; /* This creates some space between the element and the border. */
    border-bottom: 1px solid black; /* This creates the border. Replace black with whatever color you want. */
}

 img {
     max-width:100%;
     height: 400px;
     border-radius:10px;

 }
 h1 {
     font-family:'Roboto';
     text-align:left;
     
     margin: 8px;
     margin-left: 20px;
     font-size: 20px;
    text-align: left;
    padding-right:52px;
   }

   .bottomhalf {
       position:absolute;
       top:150;
       height:900px;
       
       z-index:997;
       background-color:white;
       text-align:center;
     font-family: "Carrois Gothic";
     font-size: 100px;
     font-weight:bold;
     left:0;
     right:0;
     padding-left:120px;
     padding-right:120px;
     
     
     }

     input[type="submit"] {
         background-color: whitesmoke;
         font-size: 35px;
         font-family: "Alegreya";
         font-weight: bold;
        padding: 10px;
     }
     input[type="text"]{
         height: 100px;
         width: 800px;
         font-size: 35px;
         font-family: "Alegreya";

     }
     label[for="id_word_count"] {
         display: none;
     }

     input[type=text] {
  transition: width 0.4s ease-in-out;
  outline: 0;
}

input[type=text]:focus {
  width: 70%;
}
.words {
  font-family: "Alegreya";
  font-weight: normal;
  font-size:30px;
}
.dataflex{
       display:flex;
       font-family: "Roboto Condensed";
       justify-content:center;
       padding-top:0px;
       flex-wrap: wrap;
       flex-direction:column;
       
     
     }
.title {
    font-family: 'Alegreya';
    font-size: 30px;
    text-justify: center;
    font-weight:500;
    padding-right:40px;
    text-decoration: underline;
}

a:link {
   text-decoration: none;
   color:black;
 }

 a:visited {

    color:black;
 }
 a:hover {
     text-decoration:underline;
 }
    </style></head>
<body>


        <div class="navbar-fixed-top">
            <h1>
             <a href={% url 'mainpage' %}>Headline Compare </a>
           
            </h1>
            
        </div>
        <div class="navbar-fixed-date"><div class="topdate">Word Count</div> </div>

    
        <div class="bottomhalf">
             <div class="dataflex">
   <div class="title">
       Most Common Words by Newspaper
   </div>

<div>
    {% autoescape off %}
    {{ html_div_values }}
{% endautoescape %}
</div>
        </div>
        <form action="/word_count/" method="GET">
           {% csrf_token %}
           {{form}}
            <input type="submit" value="Search">
            
            </form>

          
      

       
        </div>